import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Diego Omar Corrales - CV</title>
      </head>
      <body className="{inter.className} p-10">
        <Header />
        
        {children}
      </body>
    </html>
  )
}
